### PR TITLE
Display users list from the back-end

### PR DESCRIPTION
**Pull request by nataphilips**

### CODE REVIEW

**Comment by nataphilips** [comment]
At this point, you follow the user but the changes do not appear on the UI. I still need to create 'update state' action for this.
Re Unfollowing - can we return a friendship ID in FriendList query as well?

**Comment by nataphilips** [comment]
Re changes like following a user not appearing on the UI - had to remove caching to fix this. So now if you clear the input, you will see an updated connections list.
Worth considering how to make this action prettier on the UI and configure the cache properly, but maybe as a separate issue cause development branch is now far behind.

**Comment by samjam48** [comment]
I've sorted the return of friendship ID.

I'm confused by the use of 'subscriptions' in the state for FriendsList.jsx. I thought 'subscriptions' was a term for people subscribed to a podcast. What does it mean here? Is it to show all your friends that listen to the same podcast you do?
It's probably worth refactoring our naming conventions a little as we don't even subscribe to podcasts currently and actually subscriptions means podcasts so perhaps we should name it that...
(probably I should update user1 and user2 in friendships table, and rename the table to connections or following...)

I currently get an error when I click add a friend. It seems to send endless calls to the database and it timed out. Is it waiting for a response or something.

**Comment by nataphilips** [comment]
Sorry for the confusion, in this case, it was a list of people you're following. Not sure how to name them gracefully. It's not a friends list yet.  Maybe connections?

Regarding the error. I don't have it, can you send a screenshot? 
Top of mind reason would be - you need to hardcode your own user id (line 7 of FriendItem). Maybe the user with id #8 doesn't exist in your local db. This will be solved while working on the user profile tab - should return all the necessary info including your own ID.

**Comment by samjam48** [comment]
modules/social/actions.js
```
export const follow = (userId1, userId2) => async (dispatch) => {
	await client.mutate({
		variables: { user1_id: userId1, user2_id: userId2 },
		mutation: FollowMutation,
	})

	dispatch({
		type: 'FOLLOW',
		payload: {},
	})
}
```

We aren't doing anything with the result coming back or updating the state as to whether it worked.

When I go into the app again in the future it seems to have noticed who I added.

The constant posting graphQL queries now happens even before I click on a user. might be from the search bar.

**Comment by samjam48** [comment]
`updateState()` is also bad wording of a function.

We have a lot of state functions and different things. I have no idea what this means.

You're giving it the current users id. Could it be `updateCurrentUserID()`?

**Comment by samjam48** [comment]
### screens/social/SocialScreen.jsx

**State update**
`const [value, onChangeText] = React.useState(null)` - youshould keep naming conventions within state. This genuinely looked like not react state for a while and confused me. It should follow this rulte
e.g. `const [debouncedValue, setDebouncedValue] = useState(value)`
So I guess something like
`const [searchText, setSearchText] = useState('')`

The error I have of the back end being polled continuously as soon as I open social screen is probably due to the state of this function not being managed. I think you might need to try useEffect() to make it only run when needed.

**Comment by samjam48** [comment]
#### Error 
I found the error of constant queries.

social/index.js
```
const Social = (props) => {
	const userID = 3

	props.updateState(userID)

	return <SocialScreen {...props} />
}
```
This is constantly running `updateState()`
Which is in turn running `getConnectionsQuery` and `GetAllUsersQuery`

**Comment by nataphilips** [comment]
List of things refactored, according to our discussion:

- Renamed: subscriptions/connections to followedUsersList; follow function to followUser; state of search values 

- updateState action - removed entirely since we won't perform search on the front end. Using two separate functions: getAllUsers and getConnections to get an initial state for the front end search function. In the future, when we add a proper search query, we should remove getAllUsers action.

- Replaced two search functions (for followed and not followed users) with one action - SocialSearch. Will make it easier to implement the search query.

- Added comments for actions, commented out whatever we currently don't use 

This leaves us with only 4 actions for Social at the moment: to get the users you follow, to follow a user, to search for users and to get all users. The last one will be removed working on the next issue.

**Comment by samjam48** [comment]
Okay nice work.
Still need to hook the user search directly up to back end instead of calls to back end earlier and then searching through that.
And to implement following as seems to not work with me (perhaps just the current userID thing) which should doable once user profile stuff sorted I guess. but needs to be updated in search though

**Pull request merged**
