### PR TITLE
Storybook

### PR DESCRIPTION
**Pull request by GbengaOshinaga**
Adds storybook to the project.
Ideally, storybook should be accessed through the dev menu, but expo doesn't expose that API (please let me know if I'm wrong)
Currently, it is being added to the tabs in development mode.
Let me know if you believe if there's a better way to implement this. Thanks.

### CODE REVIEW

**Comment by caiokf** [comment]
i usually prefer to have a separate entrypoint file, a new App.jsx, where all you have is an if Constants.manifest.slug === 'storybook' and then on the package.json script you start expo passing --config to a new app.storybook.json with the new slug. It minimizes the conditional dev code mixed into production code and for me, easier to read.

**Comment by GbengaOshinaga** [comment]
@caiokf On that note, what do you think about using expobook instead? It runs the stories in a separate env. https://github.com/teamplanes/expobook

**Comment by caiokf** [comment]
@GbengaOshinaga never used but you could try, definitely, see how it looks

**Comment by samjam48** [comment]
Yea that does look cleaner! Having code in each file did feel a little messy.  Sorry for not having clearer instructions at the start.

Could you updated to 'Expobook' please?

I have updated master and dev branches so you'll need to merge dev into this branch first to avoid conflicts.

**Comment by mindsgn** [comment]
wrong branch push

**Pull request closed without merging**
