### PR TITLE
fetch user id and store user details in redux

### PR DESCRIPTION
**Pull request by aliahsan07**

### CODE REVIEW

**Comment by aliahsan07** [comment]
@nataphilips need you to go over storybook with me this week, I haven't touched that side for this ticket yet

**Comment by samjam48** [comment]
I'm getting this error when I try to login.
`Error in Logging in: Error: Network error: JSON Parse error: Unrecognized token '<'`

So it ends up just taking me back to the login screen

**Comment by nataphilips** [comment]
I'm having this error on logging in 
Screen Shot 2020-06-22 at 4 19 26 PM

**Comment by samjam48** [comment]
Yea That error was my own network your right.

But now I'm not getting error it's just not logging in. I go through log in screens and end up back where i started and can only log in again.

If I close and restart the app, when I open it I am logged in already and can't reproduce the problem.

(Profile screen looks good though 👍 )

**Pull request merged**
